import yaml
import io

class cost_factory:
    '''
    A cost factory serves all cost functions to set up a PyTr2d tracking problem.
    The individual cost functions are parametrized individually, with parameters being
    loaded from file or set programmatically.
    '''

    parameters = {
        'appearance': [
            1,          # lambda (global scaling of this cost)
            0,          # min cost
            1,          # slope
            25,         # max value
        ],
        'disappearance': [
            1,          # lambda (global scaling of this cost)
            0,          # min cost
            1,          # slope
            15,         # max value
        ],
        'movement': [
            1,          # lambda (global scaling of this cost)
            1,          # w_dist: factor for distance in pixels
            1,          # w_size: factor for difference in size
        ]
    }

    def __init__(self, parameters_yaml_file=None):
        '''
        Constructor: if filename to parameters_yaml_file is not given, default values will be used
        '''
        if parameters_yaml_file != None:
            self.load_parameters(parameters_yaml_file)

    def save_parameters(self, filename):
        '''
        Saves self.parameters in a YAML file for later reuse.
        :param filename: string pointing to the YAML file the parameters should be stored in.
        :return: nothing
        '''
        with io.open(filename, 'w', encoding='utf8') as outfile:
            yaml.dump(self.parameters, outfile, default_flow_style=False, allow_unicode=True)

    def load_parameters(self, filename):
        '''
        Loads a YAML file containing all cost funciton parameters (structure can be generated by saving a YAML
        using self.save_parameters).
        :param filename: string pointing to the YAML file the parameters should be stored in.
        :return: nothing
        '''
        with open(filename, 'r') as stream:
            self.parameters = yaml.safe_load(stream)



    def get_segmentation_cost(self,stuff,you,need):
        '''
        Explain what the f it does... and why it is negative... ;)
        :param stuff: what
        :param you: is
        :param need: this
        :return: returns the costs for an appearance event
        '''
        return 0.0

    def get_appearance_cost(self,stuff,you,need):
        '''
        Explain what the f it does...
        :param stuff: what
        :param you: is
        :param need: this
        :return: returns the costs for an appearance event
        '''
        return 0.0

    def get_disappearance_cost(self,stuff,you,need):
        '''
        Explain what the f it does...
        :param stuff: what
        :param you: is
        :param need: this
        :return: returns the costs for an appearance event
        '''
        return 0.0

    def get_movement_cost(self,stuff,you,need):
        '''
        Explain what the f it does...
        :param stuff: what
        :param you: is
        :param need: this
        :return: returns the costs for an appearance event
        '''
        return 0.0

    def get_division_cost(self,stuff,you,need):
        '''
        Explain what the f it does...
        :param stuff: what
        :param you: is
        :param need: this
        :return: returns the costs for an appearance event
        '''
        return 0.0